# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_auto_20160822_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='cluster_information',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='strand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='hmm_output',
            name='hmm_profile_key',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
